In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os
import random

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,Sequential,Model

import cv2

In [3]:
# NO CHANGING VARIABLES



In [4]:
# CHANGING VARIABLES




In [5]:
path_of_images = os.path.join("/content/drive/MyDrive/PetImages")
category = os.listdir(path_of_images)

In [6]:
# I READING THE DATA
# the index of cat = 0 ,, Dog = 1

images = []
labels = []
width = 150
hight = 150

for i in category:

  path = os.path.join(path_of_images,i)
  for img in os.listdir(path):
    img_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
    if img_array is not None:
      img_array = cv2.resize(img_array,(width,hight))
      img_array = img_array/255
      if i == "Dog":
        labels.append([i,1])
        images.append([img_array,1])
      elif i == "Cat":
        labels.append([i,0])
        images.append([img_array,0])




In [7]:
test_images = []
train_images = []
cout_cat = 0
cout_dog = 0
cats = 0
dogs = 0
test_size = 0.2

for i in range(len(images)):
  if images[i][1] == 0 :
    cout_cat += 1
  else:
    cout_dog += 1

for i in range(len(images)):
  if len(test_images) <= int(len(images)*test_size):
    if images[i][1] == 0 and cats <= int(cout_cat*test_size):
      test_images.append(images[i])
      images[i] = None
      cats += 1
    elif images[i][1] == 1 and dogs <= int(cout_dog*test_size):
      test_images.append(images[i])
      images[i] = None
      dogs += 1
  else :
    break

for i in range(len(images)):
  if images[0] == None or images[0] == [None]:
    del [images[0]]
  else:
    train_images.append(images[0])
    del [images[0]]


In [8]:
images

[]

In [9]:
print(len(train_images))
print(len(test_images))
print(len(images))

19995
4999
0


In [10]:
random.shuffle(train_images)
random.shuffle(test_images)
labels_train = np.array([ i[1] for i in train_images])
train_images = np.array([ i[0] for i in train_images])
train_images = train_images.reshape(-1,width,hight,1)
labels_test = np.array([ i[1] for i in test_images])
test_images = np.array([ i[0] for i in test_images])
test_images = test_images.reshape(-1,width,hight,1)

In [11]:
print(f"train images shape : {train_images[:2]}")
print(f"train labels shape : {labels_train[:2]}")
print(f"test images shape : {test_images[:2]}")
print(f"test labels shape : {labels_test[:2]}")

train images shape : [[[[0.70196078]
   [0.71372549]
   [0.71764706]
   ...
   [0.7254902 ]
   [0.73333333]
   [0.7372549 ]]

  [[0.70588235]
   [0.71764706]
   [0.72156863]
   ...
   [0.72156863]
   [0.72941176]
   [0.72941176]]

  [[0.70980392]
   [0.72156863]
   [0.7254902 ]
   ...
   [0.72941176]
   [0.72941176]
   [0.72941176]]

  ...

  [[0.59215686]
   [0.61568627]
   [0.61568627]
   ...
   [0.58039216]
   [0.59215686]
   [0.57647059]]

  [[0.63529412]
   [0.65098039]
   [0.65490196]
   ...
   [0.58431373]
   [0.57647059]
   [0.54117647]]

  [[0.63921569]
   [0.63529412]
   [0.6745098 ]
   ...
   [0.59215686]
   [0.55294118]
   [0.55686275]]]


 [[[0.48235294]
   [0.46666667]
   [0.4745098 ]
   ...
   [0.29019608]
   [0.14901961]
   [0.15686275]]

  [[0.47058824]
   [0.50980392]
   [0.45098039]
   ...
   [0.24313725]
   [0.23529412]
   [0.09803922]]

  [[0.43137255]
   [0.52941176]
   [0.32941176]
   ...
   [0.18823529]
   [0.23529412]
   [0.12156863]]

  ...

  [[0.32156863]
  

In [12]:
print(f"train images shape : {train_images.shape}")
print(f"train labels shape : {labels_train.shape}")
print(f"test images shape : {test_images.shape}")
print(f"test labels shape : {labels_test.shape}")

train images shape : (19995, 150, 150, 1)
train labels shape : (19995,)
test images shape : (4999, 150, 150, 1)
test labels shape : (4999,)


In [13]:
# np.save("train_images.npy",train_images)
# np.save("train_labels.npy",labels_train)
# np.save("test_images.npy",test_images)
# np.save("test_labels.npy",labels_test)

In [14]:
# train_images = np.load("train_images.npy")
# labels_train = np.load("train_labels.npy")
# test_images = np.load("test_images.npy")
# labels_test = np.load("test_labels.npy")

In [15]:
model = Sequential([

    # layers.Conv2D(128,(3,3), padding='same', activation='relu', input_shape=(width,hight,1)),
    # layers.MaxPool2D(pool_size=(2, 2),strides=(1,1),padding='same'),
    # layers.Conv2D(100,(3,3), padding='same', activation='relu'),
    # layers.MaxPool2D(pool_size=(2, 2),strides=(1,1),padding='same'),
    # layers.Conv2D(50,(3,3), padding='same', activation='relu'),
    # layers.MaxPool2D(pool_size=(2, 2),strides=(1,1),padding='same'),
    # # layers.Conv2D(77,(3,3), padding='same', activation='relu'),
    # # layers.MaxPool2D(pool_size=(2, 2),strides=(1,1),padding='same'),
    # layers.Flatten(),
    # layers.Dense(100,activation="sigmoid"),
    # layers.Dense(182,activation="sigmoid"),
    # layers.Dense(280,activation="sigmoid"), # i add this
    # layers.Dense(50,activation="sigmoid"),
    # layers.Dense(2,activation="softmax")




    layers.Conv2D(46,(3,3), padding='same', activation='relu', input_shape=(width,hight,1)),
    layers.MaxPool2D(pool_size=(2, 2),padding='same'),
    layers.Conv2D(64,(3,3), padding='same', activation='relu'),
    layers.MaxPool2D(pool_size=(2, 2),padding='same'),
    layers.Conv2D(32,(3,3), padding='same', activation='relu'),
    layers.MaxPool2D(pool_size=(2, 2),padding='same'),
    # layers.Conv2D(20,(3,3), padding='same', activation='relu'),
    # layers.MaxPool2D(pool_size=(2, 2),strides=(1,1),padding='same'),
    layers.Flatten(),
    layers.Dense(64,activation="sigmoid"),
    layers.Dense(32,activation="sigmoid"),
    layers.Dense(64,activation="sigmoid"), # i add this
    layers.Dense(16,activation="sigmoid"),
    layers.Dense(2,activation="softmax")

])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.compile(optimizer ="adam",loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x = train_images,
          y = labels_train,
          epochs=30,
          batch_size=100,
          verbose=1,
          validation_split=0.2,
          validation_batch_size=100,
          shuffle=True,
          callbacks=[tf.keras.callbacks.EarlyStopping(
                            patience=10,
                            monitor='val_accuracy',#"val_loss",
                            restore_best_weights=True)])




# x=None,
#     y=None,
#     batch_size=None,
#     epochs=1,
#     verbose='auto',
#     callbacks=None,
#     validation_split=0.0,
#     validation_data=None,
#     shuffle=True,
#     class_weight=None,
#     sample_weight=None,
#     initial_epoch=0,
#     steps_per_epoch=None,
#     validation_steps=None,
#     validation_batch_size=None,
#     validation_freq=1

In [ ]:
model.evaluate(test_images,labels_test)

In [ ]:
plt.plot(model.history.history['accuracy'])
plt.plot(model.history.history['val_accuracy'])

In [ ]:
plt.plot(model.history.history['loss'])
plt.plot(model.history.history['val_loss'])